[package]
name = "darwin-notify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
sys = []

[build-dependencies]
bindgen = "0.66.1"

[dependencies]
block = "0.1.6"
tracing = "0.1.37"
